/**
 * Canonical VajraNativeV1 ABI, transcribed 1:1 from contracts/src/VajraNativeV1.sol
 * (deployed at 0x7d17f2765bb58ceb27b9e1e52b068c72ccb8299f on Monad Mainnet, chain 143;
 * source verified on Sourcify and Monadscan).
 *
 * This is the single ABI source for the frontend. Field order in the tuple
 * definitions mirrors the Solidity struct declaration order exactly — do not
 * reorder (blueprint §18: one canonical request-field order shared with Solidity).
 */

export const VAJRA_ABI = [
  {
    type: 'constructor',
    inputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'DOMAIN_SEPARATOR',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_AUTHENTICATOR_DATA_BYTES',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_CLIENT_DATA_JSON_BYTES',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_FUTURE_SKEW',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_LIFETIME',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MAX_MEMO_BYTES',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MIN_LIFETIME',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PAYMENT_REQUEST_TYPEHASH',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'deactivatePasskey',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fulfill',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.PaymentRequest',
        components: [
          { name: 'recipient', type: 'address', internalType: 'address' },
          { name: 'payer', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'issuedAt', type: 'uint64', internalType: 'uint64' },
          { name: 'expiresAt', type: 'uint64', internalType: 'uint64' },
          { name: 'nonce', type: 'bytes32', internalType: 'bytes32' },
          { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'authMode', type: 'uint8', internalType: 'enum VajraNativeV1.AuthMode' },
          { name: 'authVersion', type: 'uint32', internalType: 'uint32' },
        ],
      },
      {
        name: 'proof',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.AuthProof',
        components: [
          { name: 'signature', type: 'bytes', internalType: 'bytes' },
          { name: 'authenticatorData', type: 'bytes', internalType: 'bytes' },
          { name: 'clientDataJSON', type: 'bytes', internalType: 'bytes' },
          { name: 'challengeIndex', type: 'uint256', internalType: 'uint256' },
          { name: 'typeIndex', type: 'uint256', internalType: 'uint256' },
          { name: 'r', type: 'bytes32', internalType: 'bytes32' },
          { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'inspect',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.PaymentRequest',
        components: [
          { name: 'recipient', type: 'address', internalType: 'address' },
          { name: 'payer', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'issuedAt', type: 'uint64', internalType: 'uint64' },
          { name: 'expiresAt', type: 'uint64', internalType: 'uint64' },
          { name: 'nonce', type: 'bytes32', internalType: 'bytes32' },
          { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'authMode', type: 'uint8', internalType: 'enum VajraNativeV1.AuthMode' },
          { name: 'authVersion', type: 'uint32', internalType: 'uint32' },
        ],
      },
      {
        name: 'proof',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.AuthProof',
        components: [
          { name: 'signature', type: 'bytes', internalType: 'bytes' },
          { name: 'authenticatorData', type: 'bytes', internalType: 'bytes' },
          { name: 'clientDataJSON', type: 'bytes', internalType: 'bytes' },
          { name: 'challengeIndex', type: 'uint256', internalType: 'uint256' },
          { name: 'typeIndex', type: 'uint256', internalType: 'uint256' },
          { name: 'r', type: 'bytes32', internalType: 'bytes32' },
          { name: 's', type: 'bytes32', internalType: 'bytes32' },
        ],
      },
      { name: 'prospectivePayer', type: 'address', internalType: 'address' },
    ],
    outputs: [
      { name: 'id', type: 'bytes32', internalType: 'bytes32' },
      { name: 'code', type: 'uint8', internalType: 'enum VajraNativeV1.ValidationCode' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'memoHashOf',
    inputs: [{ name: 'memo', type: 'bytes', internalType: 'bytes' }],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    name: 'passkeyOf',
    inputs: [{ name: 'recipient', type: 'address', internalType: 'address' }],
    outputs: [
      { name: 'qx', type: 'bytes32', internalType: 'bytes32' },
      { name: 'qy', type: 'bytes32', internalType: 'bytes32' },
      { name: 'credentialIdHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'rpIdHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'version', type: 'uint32', internalType: 'uint32' },
      { name: 'active', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'registerPasskey',
    inputs: [
      { name: 'qx', type: 'bytes32', internalType: 'bytes32' },
      { name: 'qy', type: 'bytes32', internalType: 'bytes32' },
      { name: 'credentialIdHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'rpIdHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'requestId',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.PaymentRequest',
        components: [
          { name: 'recipient', type: 'address', internalType: 'address' },
          { name: 'payer', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'issuedAt', type: 'uint64', internalType: 'uint64' },
          { name: 'expiresAt', type: 'uint64', internalType: 'uint64' },
          { name: 'nonce', type: 'bytes32', internalType: 'bytes32' },
          { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'authMode', type: 'uint8', internalType: 'enum VajraNativeV1.AuthMode' },
          { name: 'authVersion', type: 'uint32', internalType: 'uint32' },
        ],
      },
    ],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'revoke',
    inputs: [
      {
        name: 'request',
        type: 'tuple',
        internalType: 'struct VajraNativeV1.PaymentRequest',
        components: [
          { name: 'recipient', type: 'address', internalType: 'address' },
          { name: 'payer', type: 'address', internalType: 'address' },
          { name: 'amount', type: 'uint256', internalType: 'uint256' },
          { name: 'issuedAt', type: 'uint64', internalType: 'uint64' },
          { name: 'expiresAt', type: 'uint64', internalType: 'uint64' },
          { name: 'nonce', type: 'bytes32', internalType: 'bytes32' },
          { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
          { name: 'authMode', type: 'uint8', internalType: 'enum VajraNativeV1.AuthMode' },
          { name: 'authVersion', type: 'uint32', internalType: 'uint32' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rotatePasskey',
    inputs: [
      { name: 'qx', type: 'bytes32', internalType: 'bytes32' },
      { name: 'qy', type: 'bytes32', internalType: 'bytes32' },
      { name: 'credentialIdHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'rpIdHash', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'settlementOf',
    inputs: [{ name: 'requestId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      { name: 'payer', type: 'address', internalType: 'address' },
      { name: 'recipient', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'paidAt', type: 'uint64', internalType: 'uint64' },
      { name: 'memoHash', type: 'bytes32', internalType: 'bytes32' },
      { name: 'authMode', type: 'uint8', internalType: 'enum VajraNativeV1.AuthMode' },
      { name: 'authVersion', type: 'uint32', internalType: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'statusOf',
    inputs: [{ name: 'requestId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum VajraNativeV1.RequestStatus' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'PasskeyDeactivated',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'version', type: 'uint32', indexed: true, internalType: 'uint32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PasskeyRegistered',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'version', type: 'uint32', indexed: true, internalType: 'uint32' },
      { name: 'credentialIdHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'rpIdHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PasskeyRotated',
    inputs: [
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'version', type: 'uint32', indexed: true, internalType: 'uint32' },
      { name: 'credentialIdHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'rpIdHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PaymentFulfilled',
    inputs: [
      { name: 'requestId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'payer', type: 'address', indexed: true, internalType: 'address' },
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'paidAt', type: 'uint64', indexed: false, internalType: 'uint64' },
      { name: 'memoHash', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'authMode', type: 'uint8', indexed: false, internalType: 'enum VajraNativeV1.AuthMode' },
      { name: 'authVersion', type: 'uint32', indexed: false, internalType: 'uint32' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PaymentRevoked',
    inputs: [
      { name: 'requestId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'recipient', type: 'address', indexed: true, internalType: 'address' },
      { name: 'revokedAt', type: 'uint64', indexed: false, internalType: 'uint64' },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'DirectPaymentsDisabled', inputs: [] },
  {
    type: 'error',
    name: 'IncorrectValue',
    inputs: [
      { name: 'expected', type: 'uint256', internalType: 'uint256' },
      { name: 'actual', type: 'uint256', internalType: 'uint256' },
    ],
  },
  { type: 'error', name: 'InactivePasskey', inputs: [] },
  { type: 'error', name: 'InvalidNonce', inputs: [] },
  { type: 'error', name: 'InvalidPasskeyProof', inputs: [] },
  { type: 'error', name: 'InvalidTimeWindow', inputs: [] },
  { type: 'error', name: 'InvalidWalletSignature', inputs: [] },
  { type: 'error', name: 'MemoTooLong', inputs: [] },
  { type: 'error', name: 'NativeTransferFailed', inputs: [] },
  { type: 'error', name: 'RequestAlreadyPaid', inputs: [] },
  { type: 'error', name: 'RequestExpired', inputs: [] },
  { type: 'error', name: 'RequestRevoked', inputs: [] },
  {
    type: 'error',
    name: 'WrongPasskeyVersion',
    inputs: [
      { name: 'expected', type: 'uint32', internalType: 'uint32' },
      { name: 'actual', type: 'uint32', internalType: 'uint32' },
    ],
  },
  {
    type: 'error',
    name: 'WrongPayer',
    inputs: [
      { name: 'expected', type: 'address', internalType: 'address' },
      { name: 'actual', type: 'address', internalType: 'address' },
    ],
  },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'ZeroRecipient', inputs: [] },
] as const;

/** Convenience: the PaymentFulfilled event name used for receipt verification. */
export const PAYMENT_FULFILLED_EVENT = 'PaymentFulfilled' as const;
